source/api/urls.py
from django.urls import path
from api.views import  add, subtract, multiply, divide,get_token_view
app_name = 'api'

urlpatterns = [
    path('add/', add, name='add'),
    path('subtract/', subtract, name='subtract'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
    path('token/', get_token_view, name='token'),
]

source/source/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('webapp.urls'))
]

source/webapp/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view())
]

source/api/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models

# Create your models here.

source/api/views.py
import json

from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse

from django.views.decorators.csrf import ensure_csrf_cookie


@ensure_csrf_cookie
def get_token_view(request, *args):
    if request.method == 'GET':
        return HttpResponse(json.dumps({'token': "ok"}))
    return HttpResponseNotAllowed('Only GET request are allowed')


def add(request):
    if request.method=='POST':
       body = request.body
       data = json.loads(body)
       if not data.get("A") or not data.get('B'):
           response = JsonResponse({'error': 'Enter something!!'})
           response.status_code = 400
           return response
       try:
            result = int(data['A']) + int(data['B'])
            return JsonResponse({'result': result})
       except:
           response = JsonResponse({'error': "Enter only integers"})
           response.status_code = 400
           return response



def subtract(request):
    if request.method == 'POST':
        body = request.body
        data = json.loads(body)
        if not data.get("A") or not data.get('B'):
            response = JsonResponse({'error': 'Enter something!!'})
            response.status_code = 400
            return response
        try:
            result = int(data['A']) - int(data['B'])
            return JsonResponse({'result': result})
        except:
            response = JsonResponse({'error': "Enter only integers"})
            response.status_code = 400
            return response

def multiply(request):
    if request.method == 'POST':
        body = request.body
        data = json.loads(body)
        if not data.get("A") or not data.get('B'):
            response = JsonResponse({'error': 'Enter something!!'})
            response.status_code = 400
            return response
        try:
            result = int(data['A']) * int(data['B'])
            return JsonResponse({'result': result})
        except:
            response = JsonResponse({'error': "Enter only integers"})
            response.status_code = 400
            return response

def divide(request):
    if request.method == 'POST':
        body = request.body
        data = json.loads(body)
        if not data.get("A") or not data.get('B'):
            response = JsonResponse({'error': 'Enter something!!'})
            response.status_code = 400
            return response
        try:
            result = int(data['A']) / int(data['B'])
            return JsonResponse({'result': result})
        except:
            response = JsonResponse({'error': "Enter only integers"})
            response.status_code = 400
            return response

source/webapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View


class IndexView(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

source/webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <form action="">
        <label for="fnum">First number:</label><br>
        <input type="number" id="fnum" name="fnum" ><br>
        <label for="snum">Second number:</label><br>
        <input type="number" id="snum" name="snum"><br><br>
        <input type=button value="add" name=add data-url="{% url 'api:add' %}" onclick="calculateIntegers(event)">
        <input type=button value="subtract" name=subtract onclick="calculateIntegers(event)" data-url="{% url 'api:subtract' %}">
        <input type=button value="multiply" name=multiply onclick="calculateIntegers(event)" data-url="{% url 'api:multiply' %}">
        <input type=button value="divide" name=divide onclick="calculateIntegers(event)" data-url="{% url 'api:divide' %}">
    </form>
    <h3 id="result"></h3>
</div>
<script>
 function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        let cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            let cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
async function makeRequest(url, method='GET', body) {
    let headers={
        'X-CSRFToken': getCookie('csrftoken')
    }
let response = await fetch(url, {method, headers:headers, body:body});

if (response.ok) {
    return await response.json();
} else {
    let error = new Error(response.statusText);
    error.response = response;
    throw error;
}
}

async function calculateIntegers(event) {
    event.preventDefault()
    let url = event.target.dataset.url
    let a = document.getElementById('fnum').value
    let b = document.getElementById('snum').value
    let data = {"A": a, "B": b}

    try{
        let result = await makeRequest(url, "POST", JSON.stringify(data))
        let r = document.getElementById('result')
        r.innerText = result.result
    }
    catch(e){
        console.log(e);
    }

}

async function getToken(){
    await makeRequest("/api/token/")
}

window.addEventListener('load', getToken)
</script>

</body>
</html>